require 'hoe'
require './lib/activerecord/importer/version.rb'

Hoe.spec 'activerecord-importer' do
  
  self.version = ActiveRecord::Importer::VERSION
  
  self.summary = 'activerecord-importer - Another Data Importer'
  self.description = self.summary

  self.urls    = ['https://github.com/geraldb/activerecord-importer']
  
  self.author  = 'Gerald Bauer'
  self.email   = 'example@googlegroups.com'
    
  self.licenses = ['Public Domain']   
  
 self.extra_deps = [
    ## ['activerecord', '~> 3.2'],  # NB: will include activesupport,etc.
    ['activerecord-import', '~> 0.2.11']
    ### ['sqlite3',      '~> 1.3']  # NB: install on your own; remove dependency
  ]  
  
end