require 'hoe'
require './lib/tagutils/version.rb'

Hoe.spec 'tagutils' do

  self.version = TagUtils::VERSION

  self.summary = 'tagutils - tag utilities (tag, taggings, tag list, etc.)'
  self.description = summary

  self.urls    = ['https://github.com/rubylibs/tagutils']

  self.author  = 'Gerald Bauer'
  self.email   = 'ruby-talk@ruby-lang.org'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'HISTORY.md'

  self.extra_deps = [
    ['activerecord' ],
    ['props', '>=1.2.0'],
    ['logutils', '>= 0.6.1'],
    ['textutils', '>=1.4.0']   ## fix - do NOT depend on textutils - why? why not?
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.3'
  }


end
